"""empty message

Revision ID: bd166b666913
Revises: 98e84143afbc
Create Date: 2021-05-20 11:44:31.616601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd166b666913'
down_revision = '98e84143afbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('times_bought', sa.Integer(), nullable=False))
    op.add_column('product', sa.Column('views', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'views')
    op.drop_column('product', 'times_bought')
    # ### end Alembic commands ###
